export interface ProfessionServiceDef {
  id: string;
  name: string;
  duration: number;
  price: number;
  description?: string;
}

export interface ProfessionCategoryDef {
  id: string;
  label: string;
  icon: string;
  services: ProfessionServiceDef[];
}

export interface ProfessionDef {
  label: string;
  sector: string;
  categories: ProfessionCategoryDef[];
}

/**
 * Profession templates — service businesses (beauty, wellness, education).
 * Keys are used as `code` (slug). `id` is a UUID auto-generated by Prisma.
 */
export const PROFESSION_TEMPLATES: Record<string, ProfessionDef> = {
  // ─── Peluquería & barbería ────────────────────────────────────────────────
  peluqueria: {
    label: "Peluquería o barbería",
    sector: "Belleza",
    categories: [
      {
        id: "peluqueria-corte",
        label: "Corte y barbería",
        icon: "✂️",
        services: [
          { id: "peluqueria-corte-caballero", name: "Corte caballero / Barbería", duration: 30, price: 18 },
          { id: "peluqueria-corte-nino", name: "Corte niño/a", duration: 20, price: 12 },
          { id: "peluqueria-lavar-peinar", name: "Lavar y peinar", duration: 30, price: 18 },
          { id: "peluqueria-lavar-cortar", name: "Lavar, cortar y peinar (mujer)", duration: 60, price: 28 },
          { id: "peluqueria-brushing", name: "Brushing / Secado", duration: 30, price: 18 },
        ],
      },
      {
        id: "peluqueria-color",
        label: "Color y tratamientos",
        icon: "🎨",
        services: [
          { id: "peluqueria-tinte", name: "Tinte / Coloración", duration: 90, price: 50 },
          { id: "peluqueria-mechas", name: "Mechas / Balayage", duration: 165, price: 85 },
          { id: "peluqueria-decoloracion", name: "Decoloración", duration: 120, price: 70 },
          { id: "peluqueria-matizado", name: "Matizado / Toner", duration: 45, price: 30 },
          { id: "peluqueria-alisado-queratina", name: "Alisado con queratina", duration: 180, price: 90 },
          { id: "peluqueria-tratamiento-hidratacion", name: "Tratamiento hidratación profunda", duration: 45, price: 35 },
        ],
      },
      {
        id: "peluqueria-complementos",
        label: "Complementos y arreglos",
        icon: "🪒",
        services: [
          { id: "peluqueria-arreglo-barba", name: "Arreglo de barba", duration: 20, price: 12 },
          { id: "peluqueria-depilacion-ceja", name: "Definición / arreglo de cejas", duration: 15, price: 8 },
          { id: "peluqueria-manicura-semi", name: "Manicura semi-permanente", duration: 45, price: 25 },
        ],
      },
    ],
  },

  // ─── Estética ─────────────────────────────────────────────────────────────
  estetica: {
    label: "Centro de estética",
    sector: "Belleza",
    categories: [
      {
        id: "estetica-depilacion",
        label: "Depilación",
        icon: "✨",
        services: [
          { id: "estetica-depilacion-laser-piernas", name: "Depilación láser piernas completas", duration: 45, price: 60 },
          { id: "estetica-depilacion-laser-axilas", name: "Depilación láser axilas", duration: 20, price: 25 },
          { id: "estetica-depilacion-laser-bikini", name: "Depilación láser bikini", duration: 30, price: 40 },
          { id: "estetica-depilacion-cera-piernas", name: "Depilación con cera piernas", duration: 30, price: 22 },
          { id: "estetica-depilacion-cera-axilas", name: "Depilación con cera axilas", duration: 15, price: 12 },
          { id: "estetica-depilacion-cera-bikini", name: "Depilación con cera bikini", duration: 20, price: 18 },
          { id: "estetica-depilacion-facial", name: "Depilación facial (hilo/cera)", duration: 20, price: 14 },
        ],
      },
      {
        id: "estetica-facial",
        label: "Tratamientos faciales",
        icon: "🧴",
        services: [
          { id: "estetica-limpieza-facial", name: "Limpieza facial profunda", duration: 60, price: 50 },
          { id: "estetica-hidratacion-facial", name: "Hidratación facial", duration: 45, price: 40 },
          { id: "estetica-antiedad", name: "Tratamiento antiedad", duration: 75, price: 80 },
          { id: "estetica-microblading", name: "Microblading cejas", duration: 120, price: 150 },
          { id: "estetica-laminado-cejas", name: "Laminado de cejas", duration: 45, price: 35 },
          { id: "estetica-lifting-parpados", name: "Lifting de pestañas", duration: 60, price: 45 },
        ],
      },
      {
        id: "estetica-unas",
        label: "Uñas",
        icon: "💅",
        services: [
          { id: "estetica-manicura", name: "Manicura", duration: 45, price: 25 },
          { id: "estetica-pedicura", name: "Pedicura", duration: 60, price: 35 },
          { id: "estetica-manicura-semipermanente", name: "Manicura semipermanente", duration: 60, price: 35 },
          { id: "estetica-nails-gel", name: "Uñas de gel / acrílico", duration: 90, price: 55 },
        ],
      },
      {
        id: "estetica-corporal",
        label: "Tratamientos corporales",
        icon: "🌿",
        services: [
          { id: "estetica-envoltura", name: "Envoltura corporal", duration: 60, price: 65 },
          { id: "estetica-presoterapia", name: "Presoterapia", duration: 45, price: 40 },
          { id: "estetica-radiofrecuencia", name: "Radiofrecuencia corporal", duration: 45, price: 55 },
        ],
      },
    ],
  },

  // ─── Spa & bienestar ──────────────────────────────────────────────────────
  spa: {
    label: "Spa o centro de bienestar",
    sector: "Bienestar",
    categories: [
      {
        id: "spa-masajes",
        label: "Masajes",
        icon: "🤲",
        services: [
          { id: "spa-masaje-relajante-60", name: "Masaje relajante 60 min", duration: 60, price: 60 },
          { id: "spa-masaje-relajante-90", name: "Masaje relajante 90 min", duration: 90, price: 85 },
          { id: "spa-masaje-descontracturante", name: "Masaje descontracturante", duration: 50, price: 70 },
          { id: "spa-masaje-piedras", name: "Masaje con piedras calientes", duration: 75, price: 80 },
          { id: "spa-masaje-pareja", name: "Masaje de pareja", duration: 60, price: 110 },
          { id: "spa-masaje-tailandes", name: "Masaje tailandés", duration: 90, price: 85 },
        ],
      },
      {
        id: "spa-circuitos",
        label: "Circuitos y baños",
        icon: "🌊",
        services: [
          { id: "spa-circuito-aguas", name: "Circuito de aguas", duration: 90, price: 35 },
          { id: "spa-hidromasaje", name: "Bañera de hidromasaje", duration: 30, price: 25 },
          { id: "spa-sauna", name: "Sauna individual", duration: 30, price: 20 },
        ],
      },
      {
        id: "spa-corporal",
        label: "Tratamientos corporales",
        icon: "🌿",
        services: [
          { id: "spa-exfoliacion", name: "Exfoliación corporal", duration: 45, price: 55 },
          { id: "spa-envoltura-algas", name: "Envoltura de algas", duration: 60, price: 70 },
          { id: "spa-chocolaterapia", name: "Chocolaterapia", duration: 60, price: 75 },
        ],
      },
    ],
  },

  // ─── Maquillaje ───────────────────────────────────────────────────────────
  maquillaje: {
    label: "Maquillaje profesional",
    sector: "Belleza",
    categories: [
      {
        id: "maquillaje-eventos",
        label: "Maquillaje para eventos",
        icon: "💄",
        services: [
          { id: "maquillaje-novias", name: "Maquillaje de novia", duration: 90, price: 120 },
          { id: "maquillaje-evento-social", name: "Maquillaje evento social", duration: 60, price: 65 },
          { id: "maquillaje-prueba-novia", name: "Prueba de maquillaje novia", duration: 75, price: 60 },
          { id: "maquillaje-sesion-fotos", name: "Maquillaje sesión de fotos", duration: 60, price: 70 },
        ],
      },
      {
        id: "maquillaje-semipermanente",
        label: "Maquillaje semipermanente",
        icon: "✨",
        services: [
          { id: "maquillaje-microblading-cejas", name: "Microblading cejas", duration: 120, price: 150 },
          { id: "maquillaje-micropigmentacion-labios", name: "Micropigmentación labios", duration: 120, price: 170 },
          { id: "maquillaje-delineado-permanente", name: "Delineado permanente ojos", duration: 90, price: 140 },
        ],
      },
    ],
  },

  // ─── Tatuajes y piercings ─────────────────────────────────────────────────
  tatuajes: {
    label: "Tatuajes y piercings",
    sector: "Belleza",
    categories: [
      {
        id: "tatuajes-tattoo",
        label: "Tatuajes",
        icon: "🖊️",
        services: [
          { id: "tatuajes-diseno-pequeno", name: "Tatuaje pequeño (< 5 cm)", duration: 60, price: 80, description: "Precio orientativo, varía según complejidad." },
          { id: "tatuajes-diseno-mediano", name: "Tatuaje mediano", duration: 120, price: 150, description: "Precio orientativo." },
          { id: "tatuajes-consulta-diseno", name: "Consulta y diseño personalizado", duration: 60, price: 0 },
          { id: "tatuajes-retoque", name: "Retoque de tatuaje", duration: 30, price: 30 },
        ],
      },
      {
        id: "tatuajes-piercing",
        label: "Piercings",
        icon: "💎",
        services: [
          { id: "tatuajes-piercing-oreja", name: "Piercing oreja (cartílago/lóbulo)", duration: 15, price: 30 },
          { id: "tatuajes-piercing-nariz", name: "Piercing nariz", duration: 15, price: 35 },
          { id: "tatuajes-piercing-ombligo", name: "Piercing ombligo", duration: 15, price: 35 },
        ],
      },
    ],
  },

  // ─── Fisioterapia ─────────────────────────────────────────────────────────
  fisio: {
    label: "Fisioterapia o rehabilitación",
    sector: "Salud y Bienestar",
    categories: [
      {
        id: "fisio-sesiones",
        label: "Sesiones",
        icon: "🏥",
        services: [
          { id: "fisio-primera-consulta", name: "Primera consulta / Valoración", duration: 60, price: 55 },
          { id: "fisio-sesion-general", name: "Sesión de fisioterapia", duration: 50, price: 48 },
          { id: "fisio-sesion-domicilio", name: "Sesión a domicilio", duration: 60, price: 65 },
        ],
      },
      {
        id: "fisio-terapias",
        label: "Terapias manuales",
        icon: "🤲",
        services: [
          { id: "fisio-masaje-descarga", name: "Masaje de descarga muscular", duration: 45, price: 45 },
          { id: "fisio-drenaje-linfatico", name: "Drenaje linfático manual", duration: 60, price: 50 },
          { id: "fisio-osteopatia", name: "Osteopatía", duration: 60, price: 60 },
          { id: "fisio-puncion-seca", name: "Punción seca", duration: 30, price: 40 },
        ],
      },
      {
        id: "fisio-tecnologias",
        label: "Electroterapia",
        icon: "⚡",
        services: [
          { id: "fisio-ultrasonidos", name: "Ultrasonidos / TENS", duration: 20, price: 25 },
          { id: "fisio-ondas-de-choque", name: "Ondas de choque", duration: 20, price: 45 },
        ],
      },
    ],
  },

  // ─── Psicología ───────────────────────────────────────────────────────────
  psicologia: {
    label: "Psicología o terapia",
    sector: "Salud y Bienestar",
    categories: [
      {
        id: "psicologia-terapia",
        label: "Sesiones de terapia",
        icon: "🧠",
        services: [
          { id: "psicologia-primera-sesion", name: "Primera sesión / evaluación", duration: 60, price: 80 },
          { id: "psicologia-sesion-individual", name: "Sesión individual", duration: 50, price: 70 },
          { id: "psicologia-sesion-pareja", name: "Sesión de pareja", duration: 60, price: 90 },
          { id: "psicologia-online", name: "Sesión online", duration: 50, price: 60 },
        ],
      },
    ],
  },

  // ─── Nutrición ────────────────────────────────────────────────────────────
  nutricion: {
    label: "Nutrición o dietética",
    sector: "Salud y Bienestar",
    categories: [
      {
        id: "nutricion-consultas",
        label: "Consultas",
        icon: "🥗",
        services: [
          { id: "nutricion-primera-consulta", name: "Primera consulta nutricional", duration: 60, price: 70 },
          { id: "nutricion-seguimiento", name: "Seguimiento nutricional", duration: 30, price: 45 },
          { id: "nutricion-plan", name: "Plan dietético personalizado", duration: 45, price: 55 },
          { id: "nutricion-deportiva", name: "Nutrición deportiva", duration: 60, price: 75 },
        ],
      },
    ],
  },

  // ─── Yoga / Pilates / Fitness ─────────────────────────────────────────────
  yoga_pilates: {
    label: "Yoga, pilates o fitness",
    sector: "Bienestar",
    categories: [
      {
        id: "yoga-clases",
        label: "Clases individuales",
        icon: "🧘",
        services: [
          { id: "yoga-clase-individual", name: "Clase individual de yoga", duration: 60, price: 50 },
          { id: "pilates-clase-individual", name: "Clase individual de pilates", duration: 60, price: 55 },
          { id: "pilates-reformer", name: "Pilates en reformer (individual)", duration: 60, price: 65 },
          { id: "entrenamiento-personal", name: "Entrenamiento personal", duration: 60, price: 55 },
        ],
      },
    ],
  }, 

  // ─── Podología ────────────────────────────────────────────────────────────
  podologia: {
    label: "Podología",
    sector: "Salud y Bienestar",
    categories: [
      {
        id: "podologia-consultas",
        label: "Consultas y tratamientos",
        icon: "🦶",
        services: [
          { id: "podologia-primera-consulta", name: "Primera consulta podológica", duration: 45, price: 40 },
          { id: "podologia-quiropodia", name: "Quiropodia (durezas/callos)", duration: 45, price: 35 },
          { id: "podologia-onicocriptosis", name: "Uña encarnada", duration: 30, price: 40 },
          { id: "podologia-plantillas", name: "Estudio y ortesis plantar", duration: 60, price: 80 },
          { id: "podologia-verruga", name: "Tratamiento de verrugas plantares", duration: 30, price: 35 },
          { id: "podologia-pedicura-medicada", name: "Pedicura medicada", duration: 50, price: 40 },
        ],
      },
    ],
  },

  // ─── Logopedia ────────────────────────────────────────────────────────────
  logopedia: {
    label: "Logopedia / Terapia del habla",
    sector: "Salud y Bienestar",
    categories: [
      {
        id: "logopedia-sesiones",
        label: "Sesiones",
        icon: "🗣️",
        services: [
          { id: "logopedia-evaluacion", name: "Evaluación logopédica inicial", duration: 60, price: 65 },
          { id: "logopedia-sesion-infantil", name: "Sesión infantil (lenguaje/habla)", duration: 45, price: 50 },
          { id: "logopedia-sesion-adulto", name: "Sesión adulto (disfagia/voz)", duration: 45, price: 55 },
          { id: "logopedia-deglución", name: "Reeducación de la deglución", duration: 45, price: 55 },
          { id: "logopedia-online", name: "Sesión online", duration: 45, price: 45 },
        ],
      },
    ],
  },


  // ─── Coaching ─────────────────────────────────────────────────────────────
  coaching: {
    label: "Coaching y desarrollo personal",
    sector: "Bienestar",
    categories: [
      {
        id: "coaching-sesiones",
        label: "Sesiones",
        icon: "🎯",
        services: [
          { id: "coaching-sesion-individual", name: "Sesión de coaching individual", duration: 60, price: 90 },
          { id: "coaching-sesion-online", name: "Sesión online", duration: 60, price: 75 },
          { id: "coaching-asesoria-carrera", name: "Asesoría de carrera profesional", duration: 60, price: 90 },
          { id: "coaching-liderazgo", name: "Sesión liderazgo / equipos", duration: 90, price: 120 },
        ],
      },
    ],
  },

  // ─── Academia de danza / baile ────────────────────────────────────────────
  academia_danza: {
    label: "Academia de danza o baile",
    sector: "Educación",
    categories: [
      {
        id: "danza-clases-individuales",
        label: "Clases individuales",
        icon: "💃",
        services: [
          { id: "danza-clase-individual-salsa", name: "Clase individual salsa / bachata", duration: 60, price: 40 },
          { id: "danza-clase-individual-flamenco", name: "Clase individual flamenco", duration: 60, price: 45 },
          { id: "danza-clase-individual-contemporaneo", name: "Clase individual danza contemporánea", duration: 60, price: 40 },
          { id: "danza-clase-individual-ballet", name: "Clase individual ballet / clásico", duration: 60, price: 40 },
          { id: "danza-clase-individual-hip-hop", name: "Clase individual hip-hop / urbano", duration: 60, price: 38 },
        ],
      },
      {
        id: "danza-prueba-valoracion",
        label: "Prueba y valoración",
        icon: "📋",
        services: [
          { id: "danza-clase-prueba", name: "Clase de prueba", duration: 60, price: 0 },
          { id: "danza-valoracion-nivel", name: "Valoración de nivel", duration: 30, price: 0 },
        ],
      },
    ],
  },

  // ─── Academia de música ───────────────────────────────────────────────────
  academia_musica: {
    label: "Academia de música",
    sector: "Educación",
    categories: [
      {
        id: "musica-instrumentos",
        label: "Clases de instrumento",
        icon: "🎸",
        services: [
          { id: "musica-guitarra", name: "Guitarra (clásica/eléctrica/flamenca)", duration: 60, price: 35 },
          { id: "musica-piano", name: "Piano", duration: 60, price: 35 },
          { id: "musica-violin", name: "Violín", duration: 60, price: 40 },
          { id: "musica-bateria", name: "Batería / Percusión", duration: 60, price: 35 },
          { id: "musica-bajo", name: "Bajo eléctrico", duration: 60, price: 35 },
          { id: "musica-flauta", name: "Flauta / Saxofón", duration: 60, price: 38 },
          { id: "musica-ukelele", name: "Ukelele", duration: 60, price: 30 },
        ],
      },
      {
        id: "musica-canto",
        label: "Canto y teoría",
        icon: "🎤",
        services: [
          { id: "musica-canto-individual", name: "Clases de canto individual", duration: 60, price: 40 },
          { id: "musica-teoria-solfeo", name: "Teoría musical / Solfeo", duration: 60, price: 30 },
          { id: "musica-produccion", name: "Producción musical / DAW", duration: 60, price: 45 },
        ],
      },
    ],
  },

  // ─── Clases particulares ──────────────────────────────────────────────────
  clases_particulares: {
    label: "Clases particulares o academia",
    sector: "Educación",
    categories: [
      {
        id: "clases-materias",
        label: "Materias escolares",
        icon: "📚",
        services: [
          { id: "clases-matematicas", name: "Matemáticas / Ciencias", duration: 60, price: 30 },
          { id: "clases-lengua", name: "Lengua / Literatura", duration: 60, price: 28 },
          { id: "clases-historia", name: "Historia / Geografía", duration: 60, price: 28 },
          { id: "clases-fisica-quimica", name: "Física / Química", duration: 60, price: 32 },
          { id: "clases-acceso-universidad", name: "Preparación EVAU / acceso universidad", duration: 90, price: 40 },
          { id: "clases-oposiciones", name: "Preparación oposiciones", duration: 60, price: 40 },
        ],
      },
      {
        id: "clases-idiomas",
        label: "Idiomas",
        icon: "🌍",
        services: [
          { id: "clases-ingles", name: "Inglés (todos los niveles)", duration: 60, price: 30 },
          { id: "clases-frances", name: "Francés", duration: 60, price: 30 },
          { id: "clases-aleman", name: "Alemán", duration: 60, price: 32 },
          { id: "clases-italiano", name: "Italiano", duration: 60, price: 30 },
          { id: "clases-chino", name: "Chino / Japonés", duration: 60, price: 35 },
          { id: "clases-espanol-extranjeros", name: "Español para extranjeros (ELE)", duration: 60, price: 32 },
        ],
      },
      {
        id: "clases-tecnologia",
        label: "Tecnología e informática",
        icon: "💻",
        services: [
          { id: "clases-programacion", name: "Programación (Python/Web)", duration: 60, price: 40 },
          { id: "clases-informatica-basica", name: "Informática básica / Office", duration: 60, price: 28 },
          { id: "clases-diseno-grafico", name: "Diseño gráfico (Adobe/Figma)", duration: 60, price: 45 },
        ],
      },
    ],
  },

  // ─── Academia de artes marciales / deporte ────────────────────────────────
  artes_marciales: {
    label: "Artes marciales o deporte de combate",
    sector: "Bienestar",
    categories: [
      {
        id: "artes-clases",
        label: "Clases individuales",
        icon: "🥋",
        services: [
          { id: "artes-boxeo", name: "Boxeo (clase individual)", duration: 60, price: 45 },
          { id: "artes-mma", name: "MMA / Kick Boxing (individual)", duration: 60, price: 50 },
          { id: "artes-judo-jujitsu", name: "Judo / Jiu-Jitsu (individual)", duration: 60, price: 45 },
          { id: "artes-taekwondo", name: "Taekwondo (individual)", duration: 60, price: 40 },
          { id: "artes-karate", name: "Kárate (individual)", duration: 60, price: 38 },
          { id: "artes-muay-thai", name: "Muay Thai (individual)", duration: 60, price: 50 },
        ],
      },
      {
        id: "artes-valoracion",
        label: "Valoración",
        icon: "📋",
        services: [
          { id: "artes-clase-prueba", name: "Clase de prueba gratuita", duration: 60, price: 0 },
        ],
      },
    ],
  },

  // ─── Fotografía ───────────────────────────────────────────────────────────
  fotografia: {
    label: "Fotografía o estudio fotográfico",
    sector: "Servicios Profesionales",
    categories: [
      {
        id: "foto-sesiones",
        label: "Sesiones fotográficas",
        icon: "📷",
        services: [
          { id: "foto-sesion-retrato", name: "Sesión de retrato / book personal", duration: 90, price: 150 },
          { id: "foto-sesion-familia", name: "Sesión familiar", duration: 90, price: 180 },
          { id: "foto-sesion-pareja", name: "Sesión de pareja", duration: 60, price: 130 },
          { id: "foto-sesion-embarazo", name: "Sesión de embarazo", duration: 60, price: 140 },
          { id: "foto-sesion-producto", name: "Fotografía de producto (e-commerce)", duration: 120, price: 200 },
          { id: "foto-sesion-boda", name: "Reportaje de boda", duration: 480, price: 1200 },
        ],
      },
    ],
  },

};
