import type { PrismaClient } from "../generated/prisma/index.js";
import { PROFESSION_TEMPLATES } from "../data/professionTemplates.js";

/**
 * Seeds profession templates into the DB on server start (idempotent).
 * Uses `code` (slug) as the stable lookup key — `id` is a UUID auto-generated by Prisma.
 * This decouples the internal PK from the human-readable identifier.
 */
export const ensureProfessionTemplates = async (prisma: PrismaClient): Promise<void> => {
  let totalProfessions = 0;
  let totalCategories = 0;
  let totalServices = 0;

  for (const [professionCode, template] of Object.entries(PROFESSION_TEMPLATES)) {
    // Upsert by code (stable slug). id is a UUID auto-generated for new rows.
    const profession = await (prisma as any).profession.upsert({
      where: { code: professionCode },
      create: { code: professionCode, label: template.label, sector: template.sector },
      update: { label: template.label, sector: template.sector },
    });
    totalProfessions++;

    for (const cat of template.categories) {
      const category = await (prisma as any).professionCategory.upsert({
        where: { code: cat.id },
        create: { code: cat.id, professionId: profession.id, label: cat.label, icon: cat.icon },
        update: { label: cat.label, icon: cat.icon },
      });
      totalCategories++;

      for (const svc of cat.services) {
        await (prisma as any).professionService.upsert({
          where: { code: svc.id },
          create: {
            code: svc.id,
            categoryId: category.id,
            name: svc.name,
            duration: svc.duration,
            price: svc.price,
            description: svc.description ?? null,
          },
          update: {
            name: svc.name,
            duration: svc.duration,
            price: svc.price,
            description: svc.description ?? null,
          },
        });
        totalServices++;
      }
    }
  }

  console.log(
    `[templates]: ${totalProfessions} profesiones, ${totalCategories} categorías, ${totalServices} servicios sincronizados`,
  );
};
